/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mamclient_MAMPassword */

#ifndef _Included_mamclient_MAMPassword
#define _Included_mamclient_MAMPassword
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mamclient_MAMPassword
 * Method:    encryptPassword
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_mamclient_MAMPassword_encryptPassword
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
